// MenuEx.idl : IDL source for MenuEx
//

// This file will be processed by the MIDL tool to
// produce the type library (MenuEx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(EC292181-80E8-4FFC-8532-F90AE703EBF8),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMenuExImpl : IDispatch{
};
[
	uuid(FF381A0F-7990-4F44-9317-2BBB29A3A385),
	version(1.0),
]
library MenuExLib
{
	importlib("stdole2.tlb");
	[
		uuid(91F5582C-7E28-4AAD-8772-9F948EB64D91)		
	]
	coclass MenuExImpl
	{
		[default] interface IMenuExImpl;
	};
};

