// DropOnTarget.idl : IDL source for DropOnTarget
//

// This file will be processed by the MIDL tool to
// produce the type library (DropOnTarget.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(2AE1CD01-18EB-447E-B45A-FE2201CD222F),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IDropOnTargetImpl : IDispatch{
};
[
	uuid(DFDCDE05-5B70-483F-8335-6338D8B0432C),
	version(1.0),
]
library DropOnTargetLib
{
	importlib("stdole2.tlb");
	[
		uuid(8B0A9875-C9E1-4C59-8C9A-0DF0D4754EAD)		
	]
	coclass DropOnTargetImpl
	{
		[default] interface IDropOnTargetImpl;
	};
};

